### ISSUE TITLE
express路由传入回调函数  出现undefined报错  跪求一看

### ISSUE THREAD

**Issue by zhangyu0414** [zwStar/vue-meituan#4]
Error: Route.post() requires a callback function but got a [object Undefined]
    at Route.(anonymous function) [as post] (/Users/meitu/Downloads/vscode工作区/meituan-backend/node_modules/express/lib/router/route.js:202:15)
    at Function.proto.(anonymous function) [as post] (/Users/meitu/Downloads/vscode工作区/meituan-backend/node_modules/express/lib/router/index.js:510:19)
    at Object.<anonymous> (/Users/meitu/Downloads/vscode工作区/meituan-backend/routes/v1.js:29:8)
    at Module._compile (module.js:649:30)
    at loader (/Users/meitu/Downloads/vscode工作区/meituan-backend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/meitu/Downloads/vscode工作区/meituan-backend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/meitu/Downloads/vscode工作区/meituan-backend/routes/index.js:1:1)
    at Module._compile (module.js:649:30)
    at loader (/Users/meitu/Downloads/vscode工作区/meituan-backend/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/meitu/Downloads/vscode工作区/meituan-backend/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:561:32)

**Comment by zwStar** [comment]
我的项目报错吗

**Comment by zwStar** [comment]
不好意思，已经修复，请重新拉取哈

**Comment by zhangyu0414** [comment]
哈哈  是啊  server部分  express路由出现了回调函数里有undefined值  不太熟悉楼主项目  想找你看下

**Comment by zhangyu0414** [comment]
好的

**Comment by zhangyu0414** [comment]
求个互相star了

**Comment by zwStar** [comment]
请问你微信多少呢，加个好友哈
